/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.codigo;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class JIF_InformacionEmpresas extends javax.swing.JInternalFrame {

    

    /**
     * Creates new form JIF_InformacionEmpresas
     */
    public JIF_InformacionEmpresas() {
        initComponents();
//C.cargatablaEmpresa();
    }

    public JButton getBTN_editarEmpresa() {
        return BTN_editarEmpresa;
    }

    public void setBTN_editarEmpresa(JButton BTN_editarEmpresa) {
        this.BTN_editarEmpresa = BTN_editarEmpresa;
    }

    public JButton getBTN_eliminarEmpresa() {
        return BTN_eliminarEmpresa;
    }

    public void setBTN_eliminarEmpresa(JButton BTN_eliminarEmpresa) {
        this.BTN_eliminarEmpresa = BTN_eliminarEmpresa;
    }

    public JButton getBTN_nuevaEmpresa() {
        return BTN_nuevaEmpresa;
    }

    public void setBTN_nuevaEmpresa(JButton BTN_nuevaEmpresa) {
        this.BTN_nuevaEmpresa = BTN_nuevaEmpresa;
    }

    public JTable getJT_informacionEmpresas() {
        return JT_informacionEmpresas;
    }

    public void setJT_informacionEmpresas(JTable JT_informacionEmpresas) {
        this.JT_informacionEmpresas = JT_informacionEmpresas;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_informacionEmpresas = new javax.swing.JTable();
        BTN_nuevaEmpresa = new javax.swing.JButton();
        BTN_editarEmpresa = new javax.swing.JButton();
        BTN_eliminarEmpresa = new javax.swing.JButton();
        BTN_cargaEmpresas = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GETSAS - Informacion de Empresas Asociadas");
        setAutoscrolls(true);

        JT_informacionEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JT_informacionEmpresas);

        BTN_nuevaEmpresa.setText("Nueva Empresa");

        BTN_editarEmpresa.setText("Editar Empresa");

        BTN_eliminarEmpresa.setText("Eliminar Empresa");

        BTN_cargaEmpresas.setText("Carga Lista de Empresas");
        BTN_cargaEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_cargaEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_nuevaEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_editarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_eliminarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_cargaEmpresas)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_nuevaEmpresa)
                    .addComponent(BTN_editarEmpresa)
                    .addComponent(BTN_eliminarEmpresa)
                    .addComponent(BTN_cargaEmpresas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_cargaEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_cargaEmpresasActionPerformed
        // TODO add your handling code here:
        codigo C = new codigo();
        this.getJT_informacionEmpresas().setModel(C.cargatablaEmpresa());
        //this.repaint();
    }//GEN-LAST:event_BTN_cargaEmpresasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_cargaEmpresas;
    private javax.swing.JButton BTN_editarEmpresa;
    private javax.swing.JButton BTN_eliminarEmpresa;
    private javax.swing.JButton BTN_nuevaEmpresa;
    private javax.swing.JTable JT_informacionEmpresas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
